# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - APF-website

on:
  push:
    branches:
      - azure/master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: npm install and build angular app
        run: |
          npm install
          npm run build:prod:dist --if-present

      - name: Prepare deployment artifact
        run: |
          npm run build:artifact
          
      - name: Upload deployment artifact
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./deploy-artifact

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: List directory structure
        run: ls -R

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'APF-website'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0BAF46A19CD14ECCB09CCB25A152C083 }}
          package: ./APF-Party
